services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=unidb
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d unidb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go_api
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://admin:secret@db:5432/unidb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
